### ISSUE TITLE
Move back from American spellings to GB spellings

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/sr-robot3#14]
The API presented here uses US spellings in a number of places which are likely to trip up UK based competitors & mentors.

Notably where we previously had "analogue" we now have "analog": `analog_read` rather than `analogue_read`; `AnalogPins` rather than `AnaloguePin`.

**Comment by WillB97** [comment]
This was a considered decision when writing the API and has been through the review process. Both spelling are used interchangeably in electronics and fundamentally this is wrapping the Arduino API functions which are:
```c
analogRead()
digitalRead()
digitalWrite()
```

So following the spelling of the underlying functions avoids confusion for anyone looking at Arduino's docs (which are linked from ours) or who are familiar with using Arduinos.

Ultimately the robot image has already been flashed to the Raspberry Pis so it's too late to change for this year either way.

**Comment by RealOrangeOne** [comment]
I'm making the executive decision the "analog" spelling is the one we'll use. It's more common, and I highly doubt it'll trip many people up, especially as we're consistent both internally and with our documentation.

See also https://grammarist.com/spelling/analog-analogue/: 
> The spellings are largely interchangeable, though analog is usually used in relation to electronics, while analogue is often used in the sense something that bears analogy to something else.
